version: "3"

services:
  zerotier-moon:
    image: toby1991/zerotier-moon:latest
    volumes:
      - "./zerotier:/var/lib/zerotier-one"
    ports:
      - "9993:9993/udp"
    command: "-4 0.0.0.0" # your IP
    privileged: true
    restart: always
